### ISSUE TITLE
Error: cannot 'importc' variable at compile time.

### ISSUE THREAD

**Issue by akshayzawar** [SeqOne/clinvcf#1]
Hi,

I am trying to install and use clinVCF however, at the time of compilation I am getting an error. Can you please help?

```
$ nimble install --verbose
   Warning: Package 'clinvcf' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'clinvcf.nim', but a file named 'extractClinvarSet.nim' was found. This will be an error in the future.
      Hint: If this is the primary source file in the package, rename it to 'clinvcf.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'clinvcf', then move it into a 'clinvcfpkg/' subdirectory. If it's a test file or otherwise not required to build the the package 'clinvcf.nim', prevent its installation by adding `skipFiles = @["extractClinvarSet.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
  Verifying dependencies for clinvcf@0.0.1
    Reading official package list
   Checking for hts@>= 0.2.20 & <= 0.2.23
 Installing hts@>= 0.2.20 & <= 0.2.23
    Reading official package list
Downloading https://github.com/brentp/hts-nim using git
    Cloning latest tagged version: v0.2.23
     Error: Could not read package info file in /tmp/nimble_496/githubcom_brentphtsnim_0.2.20_0.2.23/hts.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     usr/lib/nim/pure/times.nim(79, 9) Error: cannot 'importc' variable at compile time.
```

**Comment by kyauy** [comment]
Hi,

Sorry I can't reproduce your issue. 

I advice you to do a clean install of nim and hts-nim as proposed by Brent Pedersen, this could do the trick.
https://github.com/brentp/hts-nim/blob/master/scripts/install.sh

Hope it help,
Kevin

**Comment by rlanos** [comment]
Hi @akshayzawar,

Thanks for your interest in clinvcf !
If you still experience issues building de the nim code and If it's not much of a trouble for you can also build the Dockerfile and launch the tool as a container.

**Comment by brentp** [comment]
FWIW, you can make a clinvcf static binary that works on most recent (and not-so recent) linux systems like this:
```
hts_nim_static_builder  -n clinvcf.nimble -s src/clinvcf.nim
```
it requires that you have docker on your system. you can see more about that, including how to run that in singularity [here](https://github.com/brentp/hts-nim#static-binary-with-singularity)

also, here's a static binary I built using that command:
[clinvcf.gz](https://github.com/SeqOne/clinvcf/files/6555453/clinvcf.gz)

just gunzip and chmod +x.
